using System.Data;
using System.Globalization;
using HospitalMobileAPPApi.Services.Reports.Helpers;
using System.Data;
using HospitalMobileAPPApi.Services.Reports.Layout;
using HospitalMobileAPPApi.Services.Reports.Models;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace HospitalMobileAPPApi.Services.Reports.Renderers;

public sealed class BillingReceiptRenderer : IReportPdfRenderer
{
    public string TemplateName => ReportTemplateNames.BillingReceipt;

    public byte[] Render(ReportDocumentContext context)
    {
        var primary = ReportDatasetResolver.ResolvePrimary(context.DataSets);
        var advance = context.DataSets.Count > 1 ? context.DataSets[1] : null;
        var branding = context.Branding;
        var first = primary.FirstRow();
        var ward = primary.GetFirstString("WARD_NM");
        var invoiceNo = primary.GetFirstString("INVOICENO");
        var isIpd = !string.IsNullOrWhiteSpace(ward);
        var title = isIpd
            ? (string.IsNullOrWhiteSpace(invoiceNo) ? "RECIEPT" : "INVOICE")
            : "RECIEPT";

        var document = Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.MarginHorizontal(0.35f, Unit.Inch);
                page.MarginVertical(0.35f, Unit.Inch);
                page.DefaultTextStyle(x => x.FontFamily(ReportTheme.FontFamily));
                page.ApplyPageBackground(branding);

                page.Content().Column(col =>
                {
                    col.Item().Element(c => c.ComposeHospitalHeader(branding));
                    col.Item().PaddingTop(8).AlignCenter().Text(title).Style(ReportTheme.Title);

                    col.Item().PaddingTop(8).Row(row =>
                    {
                        row.RelativeItem().Column(c =>
                        {
                            c.Item().Text("MR NO").Style(ReportTheme.PrescriptionLabel);
                            c.Item().Text("NAME").Style(ReportTheme.PrescriptionLabel);
                        });
                        row.RelativeItem(2).Column(c =>
                        {
                            c.Item().Text(primary.GetFirstString("MR_NO")).Style(ReportTheme.PrescriptionValue);
                            c.Item().Text(primary.GetFirstString("PATIENTNAME")).Style(ReportTheme.PrescriptionValue);
                        });
                        row.RelativeItem().Column(c =>
                        {
                            c.Item().Text("GENERATED BY").Style(ReportTheme.PrescriptionLabel);
                            c.Item().Text("PRINTED ON").Style(ReportTheme.PrescriptionLabel);
                            c.Item().Text("PRINTED BY").Style(ReportTheme.PrescriptionLabel);
                            c.Item().Text("PRINTED VIA").Style(ReportTheme.PrescriptionLabel);
                        });
                        row.RelativeItem().Column(c =>
                        {
                            c.Item().Text(primary.GetFirstString("DTL_EMPLOYEE")).Style(ReportTheme.PrescriptionValue);
                            c.Item().Text(DateTime.Now.ToString("dd-MMM-yyyy h:mm:ss tt")).Style(ReportTheme.PrescriptionValue);
                            c.Item().Text(branding.PrintedBy).Style(ReportTheme.PrescriptionValue);
                            c.Item().Text(branding.PrintedVia).Style(ReportTheme.PrescriptionValue);
                        });
                    });

                    if (isIpd)
                        col.Item().PaddingTop(6).Element(c => ComposeAdmissionBlock(c, primary));

                    col.Item().PaddingTop(8).Element(c => ComposeBillingHeader(c, primary, isIpd, invoiceNo));
                    col.Item().PaddingTop(4).Element(c => ComposeBillingDetails(c, primary, isIpd, invoiceNo));
                    col.Item().PaddingTop(8).Element(c => ComposeTotals(c, primary));
                    col.Item().PaddingTop(6).Element(c => ComposePaymentMethod(c, primary));
                    if (advance.HasRows())
                        col.Item().PaddingTop(8).Element(c => ComposeAdvancePayments(c, advance!));

                    var remarks = primary.GetFirstString("REMARKS");
                    if (!string.IsNullOrWhiteSpace(remarks))
                        col.Item().PaddingTop(6).Text($"Remarks: {remarks}").Style(ReportTheme.PrescriptionValue);

                    col.Item().PaddingTop(10).Row(row =>
                    {
                        row.RelativeItem().Column(c =>
                        {
                            c.Item().Text("Billing Officer").Style(ReportTheme.PrescriptionLabel);
                            c.Item().Text(": _________________________").Style(ReportTheme.PrescriptionValue);
                            c.Item().PaddingTop(8).Text($"Generated On: {first.GetDateTime("INVOICE_DATE").FormatDateTime("dd-MMM-yyyy")}").Style(ReportTheme.PrescriptionValue);
                        });
                        row.RelativeItem().Column(c =>
                        {
                            c.Item().AlignRight().Text("Approved By").Style(ReportTheme.PrescriptionLabel);
                            c.Item().AlignRight().Text(": _________________________").Style(ReportTheme.PrescriptionValue);
                        });
                    });
                });
            });
        });

        return document.GeneratePdf();
    }

    private static void ComposeAdmissionBlock(IContainer container, DataTable data)
    {
        container.Column(col =>
        {
            col.Item().Row(row =>
            {
                row.RelativeItem().Text("ADM NO.").Style(ReportTheme.PrescriptionLabel);
                row.RelativeItem().Text("ADM DATE").Style(ReportTheme.PrescriptionLabel);
                row.RelativeItem().Text("ADM OFF").Style(ReportTheme.PrescriptionLabel);
            });
            col.Item().Row(row =>
            {
                row.RelativeItem().Text(data.GetFirstString("ADMISSION_NO")).Style(ReportTheme.PrescriptionValue);
                row.RelativeItem().Text(data.GetFirstString("ADMISSION_DATE")).Style(ReportTheme.PrescriptionValue);
                row.RelativeItem().Text(data.GetFirstString("ADMISSION_OFFICE")).Style(ReportTheme.PrescriptionValue);
            });
            col.Item().PaddingTop(4).Row(row =>
            {
                row.RelativeItem().Text("DOCTOR").Style(ReportTheme.PrescriptionLabel);
                row.RelativeItem().Text("WARD").Style(ReportTheme.PrescriptionLabel);
                row.RelativeItem().Text("ROOM").Style(ReportTheme.PrescriptionLabel);
                row.RelativeItem().Text("BED").Style(ReportTheme.PrescriptionLabel);
            });
            col.Item().Row(row =>
            {
                row.RelativeItem().Text(data.GetFirstString("DOCTOR")).Style(ReportTheme.PrescriptionValue);
                row.RelativeItem().Text(data.GetFirstString("WARD_NM")).Style(ReportTheme.PrescriptionValue);
                row.RelativeItem().Text(data.GetFirstString("ROOM_NO")).Style(ReportTheme.PrescriptionValue);
                row.RelativeItem().Text(data.GetFirstString("BED_NAME")).Style(ReportTheme.PrescriptionValue);
            });
        });
    }

    private static void ComposeBillingHeader(IContainer container, DataTable data, bool isIpd, string invoiceNo)
    {
        var heading = isIpd
            ? (string.IsNullOrWhiteSpace(invoiceNo) ? "BILLING DETAILS" : "BILLING DETAIL")
            : "BILLING DETAILS";
        var number = isIpd
            ? (string.IsNullOrWhiteSpace(invoiceNo) ? data.GetFirstString("RECEIPT_NO") : invoiceNo)
            : data.GetFirstString("RECEIPT_NO");

        container.Row(row =>
        {
            row.RelativeItem().Text(heading).Style(ReportTheme.SectionTitle);
            row.RelativeItem().AlignRight().Text(number).Style(ReportTheme.SectionTitle);
        });
    }

    private static void ComposeBillingDetails(IContainer container, DataTable data, bool isIpd, string invoiceNo)
    {
        var groups = data.Rows.Cast<DataRow>()
            .GroupBy(r => r.GetString("BILL_CODE_NM"))
            .ToList();

        container.Column(col =>
        {
            foreach (var group in groups)
            {
                col.Item().PaddingTop(4).Text(group.Key).Style(ReportTheme.PrescriptionLabel.FontSize(10));

                var subGroups = group.GroupBy(r => r.GetString("SUB_PART")).ToList();
                var subIndex = 1;
                foreach (var subGroup in subGroups)
                {
                    var prefix = group.Key.Equals("DIAGNOSTICS CHARGES", StringComparison.OrdinalIgnoreCase)
                        ? $"{subIndex}-"
                        : " ";
                    col.Item().PaddingLeft(8).Text($"{prefix}{subGroup.Key}").Style(ReportTheme.PrescriptionValue);

                    var showQty = !string.IsNullOrWhiteSpace(invoiceNo) || isIpd;
                    if (showQty)
                    {
                        var qty = subGroup.Sum(r => r.GetDecimal("SUB_PART_QTY"));
                        if (qty > 0)
                            col.Item().PaddingLeft(16).Text($"Qty: {qty.ToString(CultureInfo.InvariantCulture)}").Style(ReportTheme.PrescriptionValue.FontSize(8));
                    }

                    var amount = subGroup.Sum(r => r.GetDecimal("SUB_PART_AMOUNT"));
                    col.Item().AlignRight().Text(amount.ToString("N2", CultureInfo.InvariantCulture)).Style(ReportTheme.PrescriptionValue);
                    subIndex++;
                }
            }
        });
    }

    private static void ComposeTotals(IContainer container, DataTable data)
    {
        container.PaddingTop(6).Table(table =>
        {
            table.ColumnsDefinition(columns =>
            {
                columns.RelativeColumn(3f);
                columns.RelativeColumn(1f);
            });

            AddTotalRow(table, "TOTAL AMOUNT", data.GetFirstDecimal("TOTAL_AMOUNT"));
            AddTotalRow(table, "DISCOUNT", data.GetFirstDecimal("DISCOUNT_AMOUNT"));
            AddTotalRow(table, "AFTER DISCOUNT", data.GetFirstDecimal("AFTER_DISCOUNT_AMOUNT"));
            AddTotalRow(table, "ADVANCE", data.GetFirstDecimal("ADVANCE_AMOUNT"));
            AddTotalRow(table, "PANEL AMOUNT", data.GetFirstDecimal("PNL_AMOUNT"));
            AddTotalRow(table, "PAID AMOUNT", data.GetFirstDecimal("PAID_AMOUNT"));
            AddTotalRow(table, "BALANCE", data.GetFirstDecimal("BALANCE_AMOUNT"));
            AddTotalRow(table, "REFUND", data.GetFirstDecimal("REFUND_AMOUNT"));
        });
    }

    private static void AddTotalRow(TableDescriptor table, string label, decimal amount)
    {
        if (amount == 0)
            return;

        table.Cell().PaddingVertical(2).Text(label).Style(ReportTheme.PrescriptionLabel);
        table.Cell().PaddingVertical(2).AlignRight().Text(amount.ToString("N2", CultureInfo.InvariantCulture)).Style(ReportTheme.PrescriptionValue.Bold());
    }

    private static void ComposePaymentMethod(IContainer container, DataTable data)
    {
        var pm = data.GetFirstString("PM_DTL1");
        if (string.IsNullOrWhiteSpace(pm))
            pm = data.GetFirstString("PM_DTL");

        if (string.IsNullOrWhiteSpace(pm))
            return;

        container.Text($"Payment Method:  {pm}").Style(ReportTheme.PrescriptionValue);
    }

    private static void ComposeAdvancePayments(IContainer container, DataTable advance)
    {
        container.Column(col =>
        {
            col.Item().Text("ADVANCE PAYMENTS").Style(ReportTheme.SectionTitle);
            col.Item().Table(table =>
            {
                table.ColumnsDefinition(columns =>
                {
                    columns.ConstantColumn(30);
                    columns.RelativeColumn(1f);
                    columns.RelativeColumn(2f);
                    columns.RelativeColumn(1f);
                });

                table.Header(header =>
                {
                    header.Cell().Text("S NO").Style(ReportTheme.PrescriptionLabel);
                    header.Cell().Text("DATE").Style(ReportTheme.PrescriptionLabel);
                    header.Cell().Text("DETAIL").Style(ReportTheme.PrescriptionLabel);
                    header.Cell().AlignRight().Text("AMOUNT PAID").Style(ReportTheme.PrescriptionLabel);
                });

                var index = 1;
                foreach (DataRow row in advance.Rows)
                {
                    table.Cell().Text(index.ToString()).Style(ReportTheme.PrescriptionValue);
                    table.Cell().Text(row.GetDateTime("SUB_PART_DATE").FormatDate("d MMM yyyy")).Style(ReportTheme.PrescriptionValue);
                    table.Cell().Text(row.GetString("PM_DTL1")).Style(ReportTheme.PrescriptionValue);
                    table.Cell().AlignRight().Text(row.GetDecimal("SUB_PART_AMOUNT").ToString("N2", CultureInfo.InvariantCulture)).Style(ReportTheme.PrescriptionValue);
                    index++;
                }
            });
        });
    }
}
