-- MOBILE_PAYMENT_QR
-- Links online payment intents to appointment snapshots + opaque QR tokens (REQ-2026-010).

BEGIN
  EXECUTE IMMEDIATE '
    CREATE SEQUENCE MOBILE_PAYMENT_QR_SEQ
      START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE '
    CREATE TABLE MOBILE_PAYMENT_QR (
      QR_ID             NUMBER(10)      NOT NULL,
      PAYMENT_ID        NUMBER(10)      NOT NULL,
      QR_TOKEN          VARCHAR2(64)    NOT NULL,
      APPOINTMENT_ID    VARCHAR2(64),
      PATIENT_NAME      VARCHAR2(120),
      DOCTOR_NAME       VARCHAR2(120),
      DEPARTMENT_ID     NUMBER(10),
      DEPARTMENT_HINT   VARCHAR2(120),
      APPOINTMENT_TIME  VARCHAR2(120),
      PURPOSE           VARCHAR2(500),
      APPT_STATUS       VARCHAR2(40),
      QR_PAYLOAD        VARCHAR2(500)   NOT NULL,
      CREATED_AT        DATE            DEFAULT SYSDATE NOT NULL,
      CONSTRAINT PK_MOBILE_PAYMENT_QR PRIMARY KEY (QR_ID),
      CONSTRAINT UK_MOBILE_PAYMENT_QR_TOKEN UNIQUE (QR_TOKEN),
      CONSTRAINT UK_MOBILE_PAYMENT_QR_PAY UNIQUE (PAYMENT_ID)
    )';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE '
    CREATE INDEX IDX_MOBILE_PAYMENT_QR_APPT
      ON MOBILE_PAYMENT_QR (APPOINTMENT_ID)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

COMMIT;
