-- MOBILE_APPOINTMENT_PREP_ALERT
-- Schedules pre-appointment fasting / preparation push notifications
-- for Radiology and Gastroenterology appointments (REQ-2026-009).

-- Sequence
BEGIN
  EXECUTE IMMEDIATE '
    CREATE SEQUENCE MOBILE_APPT_PREP_ALERT_SEQ
      START WITH 1
      INCREMENT BY 1
      NOCACHE
      NOCYCLE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- Table
BEGIN
  EXECUTE IMMEDIATE '
    CREATE TABLE MOBILE_APPOINTMENT_PREP_ALERT (
      ALERT_ID          NUMBER(10)      NOT NULL,
      APPOINTMENT_ID    VARCHAR2(64)    NOT NULL,
      MR_NO             VARCHAR2(32)    NOT NULL,
      PREP_KIND         VARCHAR2(32)    NOT NULL,
      DEPARTMENT_HINT   VARCHAR2(120),
      DOCTOR_NAME       VARCHAR2(120),
      APPOINTMENT_AT    DATE            NOT NULL,
      SEND_AT           DATE            NOT NULL,
      TITLE             VARCHAR2(200)   NOT NULL,
      BODY              VARCHAR2(1000)  NOT NULL,
      STATUS            VARCHAR2(20)    DEFAULT ''PENDING'' NOT NULL,
      SENT_AT           DATE,
      ERROR_MESSAGE     VARCHAR2(500),
      CREATED_AT        DATE            DEFAULT SYSDATE NOT NULL,
      UPDATED_AT        DATE            DEFAULT SYSDATE NOT NULL,
      CONSTRAINT PK_MOBILE_APPT_PREP_ALERT PRIMARY KEY (ALERT_ID),
      CONSTRAINT UK_MOBILE_APPT_PREP UNIQUE (APPOINTMENT_ID, PREP_KIND),
      CONSTRAINT CHK_MOBILE_APPT_PREP_KIND CHECK (PREP_KIND IN (''RADIOLOGY'', ''GASTRO'')),
      CONSTRAINT CHK_MOBILE_APPT_PREP_STATUS CHECK (STATUS IN (''PENDING'', ''SENT'', ''CANCELLED'', ''FAILED''))
    )';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE '
    CREATE OR REPLACE TRIGGER TRG_MOBILE_APPT_PREP_BI
    BEFORE INSERT ON MOBILE_APPOINTMENT_PREP_ALERT
    FOR EACH ROW
    BEGIN
      IF :NEW.ALERT_ID IS NULL THEN
        SELECT MOBILE_APPT_PREP_ALERT_SEQ.NEXTVAL INTO :NEW.ALERT_ID FROM dual;
      END IF;
    END;';
END;
/

BEGIN
  EXECUTE IMMEDIATE '
    CREATE INDEX IDX_MOBILE_APPT_PREP_DUE
      ON MOBILE_APPOINTMENT_PREP_ALERT (STATUS, SEND_AT)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE '
    CREATE INDEX IDX_MOBILE_APPT_PREP_MR
      ON MOBILE_APPOINTMENT_PREP_ALERT (MR_NO, STATUS)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

COMMIT;
