-- MOBILE_APPOINTMENT_CONFIRM_QR
-- Opaque QR tokens for appointment confirmation PDFs (REQ-2026-014).
-- Hospital check-in scanners hit /api/AppointmentConfirmation/qr/{token}.

BEGIN
  EXECUTE IMMEDIATE '
    CREATE SEQUENCE MOBILE_APPT_CONFIRM_QR_SEQ
      START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE '
    CREATE TABLE MOBILE_APPOINTMENT_CONFIRM_QR (
      QR_ID             NUMBER(10)      NOT NULL,
      APPOINTMENT_ID    VARCHAR2(64)    NOT NULL,
      QR_TOKEN          VARCHAR2(64)    NOT NULL,
      MR_NO             VARCHAR2(32),
      PATIENT_NAME      VARCHAR2(120),
      PHONE             VARCHAR2(40),
      DOCTOR_NAME       VARCHAR2(120),
      DEPARTMENT_ID     NUMBER(10),
      DEPARTMENT_HINT   VARCHAR2(120),
      APPOINTMENT_TIME  VARCHAR2(120),
      PURPOSE           VARCHAR2(500),
      APPT_STATUS       VARCHAR2(40),
      QR_PAYLOAD        VARCHAR2(500)   NOT NULL,
      CREATED_AT        DATE            DEFAULT SYSDATE NOT NULL,
      CONSTRAINT PK_MOBILE_APPT_CONFIRM_QR PRIMARY KEY (QR_ID),
      CONSTRAINT UK_MOBILE_APPT_CONFIRM_TOKEN UNIQUE (QR_TOKEN),
      CONSTRAINT UK_MOBILE_APPT_CONFIRM_APPT UNIQUE (APPOINTMENT_ID)
    )';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE '
    CREATE INDEX IDX_MOBILE_APPT_CONFIRM_MR
      ON MOBILE_APPOINTMENT_CONFIRM_QR (MR_NO)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

COMMIT;
