-- App lock PIN hash storage for patient portal.
-- Compatible with Oracle 11g / 12c+ (sequence + trigger — no IDENTITY column).

CREATE SEQUENCE PATIENT_APP_PIN_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE PATIENT_APP_PIN (
    PIN_ID          NUMBER         NOT NULL,
    MR_NO           VARCHAR2(20)   NOT NULL,
    PIN_HASH        VARCHAR2(128)  NOT NULL,
    DEVICE_LABEL    VARCHAR2(120),
    CREATED_AT      DATE           DEFAULT SYSDATE NOT NULL,
    UPDATED_AT      DATE           DEFAULT SYSDATE NOT NULL,
    IS_ACTIVE       CHAR(1)        DEFAULT 'Y' NOT NULL,
    CONSTRAINT PK_PATIENT_APP_PIN PRIMARY KEY (PIN_ID),
    CONSTRAINT CHK_PAT_APP_PIN_ACTIVE CHECK (IS_ACTIVE IN ('Y', 'N'))
);

CREATE OR REPLACE TRIGGER TRG_PATIENT_APP_PIN_BI
BEFORE INSERT ON PATIENT_APP_PIN
FOR EACH ROW
BEGIN
    IF :NEW.PIN_ID IS NULL THEN
        SELECT PATIENT_APP_PIN_SEQ.NEXTVAL
          INTO :NEW.PIN_ID
          FROM DUAL;
    END IF;
END;
/

CREATE UNIQUE INDEX PATIENT_APP_PIN_MR_UK
    ON PATIENT_APP_PIN (MR_NO);

CREATE INDEX PATIENT_APP_PIN_ACTIVE_IDX
    ON PATIENT_APP_PIN (MR_NO, IS_ACTIVE);

COMMENT ON TABLE PATIENT_APP_PIN IS
    'Hashed app-lock PIN per patient — set/reset after OTP verification on Forgot PIN.';
