-- Patient notification inbox (FCM history) for mobile portal.
-- Run as the HMIS mobile-portal schema user (same as PATIENT_DEVICE_TOKEN).
-- Compatible with Oracle 11g / 12c+ (sequence + trigger — no IDENTITY column).

CREATE SEQUENCE PATIENT_NOTIFICATION_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE PATIENT_NOTIFICATION (
    NOTIFICATION_ID   NUMBER        NOT NULL,
    MR_NO             VARCHAR2(20)  NOT NULL,
    NOTIFICATION_TYPE VARCHAR2(50)  NOT NULL,
    CATEGORY          VARCHAR2(30)  DEFAULT 'general' NOT NULL,
    PRIORITY          VARCHAR2(10)  DEFAULT 'normal' NOT NULL,
    TITLE             VARCHAR2(200) NOT NULL,
    BODY              VARCHAR2(1000) NOT NULL,
    PAYLOAD_JSON      CLOB,
    IS_READ           CHAR(1)       DEFAULT 'N' NOT NULL,
    CREATED_AT        DATE          DEFAULT SYSDATE NOT NULL,
    READ_AT           DATE,
    CONSTRAINT PK_PATIENT_NOTIFICATION PRIMARY KEY (NOTIFICATION_ID),
    CONSTRAINT CHK_PAT_NOTIF_IS_READ CHECK (IS_READ IN ('Y', 'N'))
);

CREATE OR REPLACE TRIGGER TRG_PATIENT_NOTIFICATION_BI
BEFORE INSERT ON PATIENT_NOTIFICATION
FOR EACH ROW
BEGIN
    IF :NEW.NOTIFICATION_ID IS NULL THEN
        SELECT PATIENT_NOTIFICATION_SEQ.NEXTVAL
          INTO :NEW.NOTIFICATION_ID
          FROM DUAL;
    END IF;
END;
/

CREATE INDEX IDX_PAT_NOTIF_MR_CREATED
    ON PATIENT_NOTIFICATION (MR_NO, CREATED_AT DESC);

CREATE INDEX IDX_PAT_NOTIF_MR_UNREAD
    ON PATIENT_NOTIFICATION (MR_NO, IS_READ, CREATED_AT DESC);
