-- Patient recent activity feed for mobile portal dashboard.
-- Run as the HMIS mobile-portal schema user (same as PATIENT_NOTIFICATION).
-- Compatible with Oracle 11g / 12c+ (sequence + trigger — no IDENTITY column).

CREATE SEQUENCE PATIENT_RECENT_ACTIVITY_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE PATIENT_RECENT_ACTIVITY (
    ACTIVITY_ID    NUMBER         NOT NULL,
    MR_NO          VARCHAR2(20)   NOT NULL,
    ACTIVITY_KEY   VARCHAR2(120)  NOT NULL,
    KIND           VARCHAR2(30)   NOT NULL,
    TITLE          VARCHAR2(200)  NOT NULL,
    SUBTITLE       VARCHAR2(200),
    PAYLOAD_JSON   CLOB,
    VIEWED_AT      DATE           DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_PATIENT_RECENT_ACTIVITY PRIMARY KEY (ACTIVITY_ID),
    CONSTRAINT UK_PAT_RECENT_ACT_MR_KEY UNIQUE (MR_NO, ACTIVITY_KEY)
);

CREATE OR REPLACE TRIGGER TRG_PATIENT_RECENT_ACTIVITY_BI
BEFORE INSERT ON PATIENT_RECENT_ACTIVITY
FOR EACH ROW
BEGIN
    IF :NEW.ACTIVITY_ID IS NULL THEN
        SELECT PATIENT_RECENT_ACTIVITY_SEQ.NEXTVAL
          INTO :NEW.ACTIVITY_ID
          FROM DUAL;
    END IF;
END;
/

CREATE INDEX IDX_PAT_RECENT_ACT_MR_VIEWED
    ON PATIENT_RECENT_ACTIVITY (MR_NO, VIEWED_AT DESC);

COMMENT ON TABLE PATIENT_RECENT_ACTIVITY IS
    'Dashboard recent-activity rows for logged-in patients (max 3 kept by API).';
