-- Trusted login devices for hybrid OTP-on-new-device flow.
-- Run as the HMIS mobile-portal schema user (same as PATIENT_DEVICE_TOKEN).
-- Compatible with Oracle 11g / 12c+ (sequence + trigger — no IDENTITY column).

CREATE SEQUENCE PATIENT_TRUSTED_DEVICE_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE PATIENT_TRUSTED_DEVICE (
    TRUSTED_DEVICE_ID   NUMBER        NOT NULL,
    MR_NO               VARCHAR2(20)  NOT NULL,
    DEVICE_INSTALL_ID   VARCHAR2(64)  NOT NULL,
    TRUST_TOKEN_HASH    VARCHAR2(128) NOT NULL,
    DEVICE_LABEL        VARCHAR2(120),
    PLATFORM            VARCHAR2(20),
    TRUSTED_AT          DATE          DEFAULT SYSDATE NOT NULL,
    LAST_LOGIN_AT       DATE,
    EXPIRES_AT          DATE          NOT NULL,
    IS_ACTIVE           CHAR(1)       DEFAULT 'Y' NOT NULL,
    CONSTRAINT PK_PATIENT_TRUSTED_DEVICE PRIMARY KEY (TRUSTED_DEVICE_ID),
    CONSTRAINT CHK_PAT_TRUST_DEV_ACTIVE CHECK (IS_ACTIVE IN ('Y', 'N'))
);

CREATE OR REPLACE TRIGGER TRG_PATIENT_TRUSTED_DEVICE_BI
BEFORE INSERT ON PATIENT_TRUSTED_DEVICE
FOR EACH ROW
BEGIN
    IF :NEW.TRUSTED_DEVICE_ID IS NULL THEN
        SELECT PATIENT_TRUSTED_DEVICE_SEQ.NEXTVAL
          INTO :NEW.TRUSTED_DEVICE_ID
          FROM DUAL;
    END IF;
END;
/

CREATE UNIQUE INDEX PATIENT_TRUSTED_DEVICE_UK
    ON PATIENT_TRUSTED_DEVICE (MR_NO, DEVICE_INSTALL_ID);

CREATE INDEX PATIENT_TRUSTED_DEVICE_MR_IDX
    ON PATIENT_TRUSTED_DEVICE (MR_NO, IS_ACTIVE, EXPIRES_AT);

COMMENT ON TABLE PATIENT_TRUSTED_DEVICE IS
    'Patient devices trusted after login OTP verification — enables password-only login on known devices.';
