-- Patient profile photo for mobile app (path stored; file on API wwwroot).
-- Run as the HMIS mobile-portal schema user (same as PATIENT_DEVICE_TOKEN).
-- Compatible with Oracle 11g / 12c+ (sequence + trigger — no IDENTITY column).

CREATE SEQUENCE PATIENT_PROFILE_PHOTO_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE PATIENT_PROFILE_PHOTO (
    PHOTO_ID        NUMBER         NOT NULL,
    MR_NO           VARCHAR2(20)   NOT NULL,
    IMAGE_PATH      VARCHAR2(500)  NOT NULL,
    CONTENT_TYPE    VARCHAR2(100),
    FILE_SIZE       NUMBER,
    CREATED_AT      DATE           DEFAULT SYSDATE NOT NULL,
    UPDATED_AT      DATE           DEFAULT SYSDATE NOT NULL,
    IS_ACTIVE       CHAR(1)        DEFAULT 'Y' NOT NULL,
    CONSTRAINT PK_PATIENT_PROFILE_PHOTO PRIMARY KEY (PHOTO_ID),
    CONSTRAINT CHK_PAT_PROF_PHOTO_ACTIVE CHECK (IS_ACTIVE IN ('Y', 'N'))
);

CREATE OR REPLACE TRIGGER TRG_PATIENT_PROFILE_PHOTO_BI
BEFORE INSERT ON PATIENT_PROFILE_PHOTO
FOR EACH ROW
BEGIN
    IF :NEW.PHOTO_ID IS NULL THEN
        SELECT PATIENT_PROFILE_PHOTO_SEQ.NEXTVAL
          INTO :NEW.PHOTO_ID
          FROM DUAL;
    END IF;
END;
/

CREATE UNIQUE INDEX PATIENT_PROFILE_PHOTO_MR_UK
    ON PATIENT_PROFILE_PHOTO (MR_NO);

CREATE INDEX PATIENT_PROFILE_PHOTO_ACTIVE_IDX
    ON PATIENT_PROFILE_PHOTO (IS_ACTIVE, UPDATED_AT DESC);

COMMENT ON TABLE PATIENT_PROFILE_PHOTO IS
    'Mobile app patient profile photos — IMAGE_PATH is relative under wwwroot (e.g. uploads/profiles/...).';
